apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-default-ado
  name: ado
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-ado
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-ado
    spec:
      containers:
      - name: ado
        image: c.p1kachu.net/ado
        ports:
        - containerPort: 9292
          name: 9292tcp802
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 9292
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 9292
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 2
          timeoutSeconds: 2
        resources: {}
      imagePullSecrets:
      - name: p1kachu
      - name: c.p1kachu.net

---
apiVersion: v1
kind: Service
metadata:
  name: ado
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9292tcp802
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-ado

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ado
  namespace: default
spec:
  rules:
    - host: ad.app.p1kachu.net
      http:
        paths:
          - backend:
              service:
                name: ado
                port:
                  number: 80
            path: /
            pathType: Prefix 
  tls:
    - hosts:
        - ad.app.p1kachu.net
      secretName: wild-cert
