kind: DaemonSet
apiVersion: apps/v1
metadata:
  namespace: traefik
  name: traefik-deployment
  labels:
    app: traefik
spec:
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v2.9@sha256:8d81a9df1435f9f3d36ac9398465ef2d5d61e671059974db753faaed14b627de
          args:
            - --api.insecure
            - --entrypoints.web.Address=:80
            - --entrypoints.websecure.Address=:443
            - --entrypoints.websecure.http.tls
            - --providers.kubernetesingress
            - --providers.kubernetescrd
            - --ping=true
            - --ping.entrypoint=ping
            - --entrypoints.ping.Address=:9000
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: dashboard
              containerPort: 8080
            - name: ping
              containerPort: 9000
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /ping
              port: ping
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: ping
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: "64Mi"
              cpu: "250m"      

---
apiVersion: v1
kind: Service
metadata:
  namespace: traefik
  name: traefik-dashboard-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    app: traefik
