kind: Deployment
apiVersion: apps/v1
metadata:
  name: logo
  labels:
    app: logo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logo
  template:
    metadata:
      labels:
        app: logo
    spec:
      containers:
        - name: darkhttpd
          image: nrt.ocir.io/nrdcprlzxgzg/public/yuzu-test@sha256:1ee77fa8e32a6d424a4b0720eb4c8ecb112942011f73427283dbd20d0bf3ac78
          ports:
            - name: web
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: logo
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
  selector:
    app: logo

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logo-tls-ingress
spec:
  tls:
  - hosts:
      - '*.yuzu.p1kachu.net'
      - yuzu.p1kachu.net
    secretName: yuzu-wild
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: logo
            port:
              name: web
