---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hayate-rustfs
  namespace: default
automountServiceAccountToken: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hayate-rustfs-config
  namespace: default
data:
  RUSTFS_ADDRESS: ":9000"
  RUSTFS_CONSOLE_ADDRESS: ":9001"
  RUSTFS_CONSOLE_ENABLE: "true"
  RUSTFS_OBS_LOG_DIRECTORY: "/logs"
  RUSTFS_OBS_LOGGER_LEVEL: "info"
  RUSTFS_OBS_ENVIRONMENT: "development"
  RUSTFS_REGION: "ap-northeast-1"
  RUSTFS_VOLUMES: "/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: hayate-rustfs-logs
  namespace: default
spec:
  accessModes: [ ReadWriteOnce ]
  storageClassName: local-path
  resources:
    requests:
      storage: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: hayate-rustfs
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 9000
    - name: endpoint
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
  selector:
    app.kubernetes.io/name: rustfs
    app.kubernetes.io/instance: hayate-rustfs

---
apiVersion: v1
kind: Service
metadata:
  name: hayate-rustfs-console
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 9001
  selector:
    app.kubernetes.io/name: rustfs
    app.kubernetes.io/instance: hayate-rustfs

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hayate-rustfs
  namespace: default
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: rustfs
      app.kubernetes.io/instance: hayate-rustfs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rustfs
        app.kubernetes.io/instance: hayate-rustfs
    spec:
      imagePullSecrets:
        []
      nodeSelector:
        kubernetes.io/hostname: "juno4a"
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsUser: 10001
      initContainers:
        - name: init-step
          image: "busybox:1.37.0@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          command:
            - sh
            - -c
            - |
              mkdir -p /data /mnt/rustfs/logs
              chmod 755 /mnt/rustfs/logs
          volumeMounts:
            - name: data
              mountPath: /data
            - name: logs
              mountPath: /mnt/rustfs
      containers:
        - name: rustfs
          image: "rustfs/rustfs:1.0.0-alpha.85@sha256:23ff2af1ec2d64e0fb9608a1c39b5eb96fcff3a8efecf332986c948b0e3e4f8a"
          command: ["/usr/bin/rustfs"]
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          ports:
            - name: endpoint
              containerPort: 9000
            - name: console
              containerPort: 9001
          envFrom:
            - configMapRef:
                name: hayate-rustfs-config
            - secretRef:
                name: rustfs-secret
          resources:
            {}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: endpoint
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/ready
              port: endpoint
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          volumeMounts:
            - name: logs
              mountPath: /logs
              subPath: logs
            - name: data
              mountPath: /data
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: hayate-rustfs-logs
        - name: data
          hostPath:
            path: /media/Hayate/rustfs-data
            type: DirectoryOrCreate
