apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-default-lavalink-musicbot
  name: lavalink-musicbot
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-lavalink-musicbot
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-lavalink-musicbot
    spec:
      containers:
      - image: c.p1kachu.net/lavalink-musicbot
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 2
          timeoutSeconds: 2
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: DEFAULT_VOLUME
          value: "10"
        - name: ENABLE_SPOTIFY
          value: "false"
        - name: LAVA_HOST
          value: lavalink.default
        - name: LAVA_PASS
          value: "crumpet-stuffy-encourage"
        - name: LAVA_PORT
          value: "8080"
        - name: OWNER_ID
          value: "455614659324542976"
        - name: PREFIX
          value: '!'
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              key: TOKEN
              name: orpheus-token
        name: lavalink-musicbot
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
        resources: {}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: p1kachu
      - name: c.p1kachu.net
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
