apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-default-speedtest
  name: speedtest
  namespace: default
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-speedtest
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-speedtest
    spec:
      containers:
      - env:
        - name: MODE
          value: standalone
        image: ghcr.io/librespeed/speedtest:5.5@sha256:1c8ca636a9b68d023c819c5ce6e7fab3f5214b963138eb9ef6aaddf9ae111c77
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        name: speedtest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: speedtest
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-speedtest
  sessionAffinity: None
  type: LoadBalancer
