apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-default-speedtest
  name: speedtest
  namespace: default
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-speedtest
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-speedtest
    spec:
      nodeName: juno4a
      containers:
      - env:
        - name: MODE
          value: standalone
        image: ghcr.io/librespeed/speedtest:6.1@sha256:b6b0890047e833158370d59ed5ef289b3e67a58f4a363cd37ef5c09d170d8543
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        name: speedtest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: speedtest
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-speedtest
  sessionAffinity: None
  type: LoadBalancer
