apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: dii
  namespace: metallb-system
spec:
  ipAddressPools:
  - dii
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: juno4a
  interfaces:
  - eno1
