---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wild-cert-staging
  namespace: default
  labels:
    use-cloudflare-solver: 'true'
spec:
  secretName: wild-cert-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: p1kachu.net
  dnsNames:
    - p1kachu.net
    - '*.p1kachu.net'
    - '*.app.p1kachu.net'
    - xn--gckj0erd4d.net
    - '*.xn--gckj0erd4d.net'

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zeropixel-cert
  namespace: default
  labels:
    use-cloudflare-solver: "true"
spec:
  secretName: zeropixel-cert
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  commonName: 0px.org
  dnsNames:
  - 0px.org
  - '*.0px.org'
