
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-default-sorry
  name: sorry
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-sorry
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        {}
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-sorry
    spec:
      containers:
      - name: sorry
        image: nrt.ocir.io/nrdcprlzxgzg/public/sorry
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 2
          timeoutSeconds: 2
        resources: {}
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: sorry
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-sorry

