---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archivebox
spec:
  selector:
    matchLabels:
      app: archivebox
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: archivebox
    spec:
      initContainers:
      - name: init-archivebox
        image: archivebox/archivebox
        args: ['init']
        volumeMounts:
          - mountPath: /data
            name: archivebox
      containers:
        - name: archivebox
          args: ["server", "--quick-init", "0.0.0.0:8000"]
          image: archivebox/archivebox
          ports:
            - containerPort: 8000
              protocol: TCP
              name: http
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          volumeMounts:
            - mountPath: /data
              name: archivebox
      restartPolicy: Always
      volumes:
        - name: archivebox
          persistentVolumeClaim:
            claimName: archivebox
---
apiVersion: v1
kind: Service
metadata:
  name: archivebox
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: archivebox

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: archivebox-admin
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: traefik-superbasic@kubernetescrd
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: archivebox-admin.app.p1kachu.net
      http:
        paths:
          - backend:
              service:
                name: archivebox
                port:
                  number: 80
            path: /
            pathType: Prefix 
  tls:
    - hosts:
        - archivebox-admin.app.p1kachu.net
      secretName: wild-cert
