apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-default-battle
  name: battle
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-battle
  template:
    metadata:
      labels:
        app: battle-saikoh-tk
        workload.user.cattle.io/workloadselector: deployment-default-battle
    spec:
      containers:
      - name: battle
        env:
        - name: PORT
          value: "8124"
        - name: REDIS_URL
          value: redis://redis.shared:6379/
        image: c.p1kachu.net/battle
        imagePullPolicy: Always
        ports:
        - containerPort: 8124
          name: http-alt
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8124
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        resources: {}
      imagePullSecrets:
      - name: c.p1kachu.net

---
apiVersion: v1
kind: Service
metadata:
  name: battle
spec:
  ports:
    - name: http
      port: 80
      targetPort: http-alt
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-battle

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: battle
  namespace: default
spec:
  rules:
    - host: battle.saikoh.uk
      http:
        paths:
          - backend:
              service:
                name: battle
                port:
                  number: 80
            path: /
            pathType: Prefix 
  tls:
    - hosts:
        - battle.saikoh.uk
      secretName: battle-saikoh-cert
