---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zeropixel-cert
  namespace: default
  labels:
    use-cloudflare-solver: "true"
spec:
  secretName: zeropixel-cert
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  commonName: 0px.org
  dnsNames:
  - 0px.org
  - '*.0px.org'

---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: battle-saikoh-cert
#  namespace: default
#spec:
#  secretName: battle-saikoh-cert
#  issuerRef:
#    kind: ClusterIssuer
#    name: letsencrypt-production
#  commonName: battle.saikoh.uk
#  dnsNames:
#  - battle.saikoh.uk
#
