apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-default-saas
  name: saas
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-saas
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-saas
    spec:
      containers:
      - name: saas
        image: c.p1kachu.net/saas
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http-alt
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        resources: {}
      imagePullSecrets:
      - name: c.p1kachu.net

---
apiVersion: v1
kind: Service
metadata:
  name: saas
spec:
  ports:
    - name: http
      port: 80
      targetPort: http-alt
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-saas

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saas
  namespace: default
spec:
  rules:
    - host: saas.app.p1kachu.net
      http:
        paths:
          - backend:
              service:
                name: saas
                port:
                  number: 80
            path: /
            pathType: Prefix 
  tls:
    - hosts:
        - saas.app.p1kachu.net
      secretName: wild-cert
