apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-pikabot-swc08
  name: swc08
  namespace: pikabot
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-pikabot-swc08
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-pikabot-swc08
    spec:
      containers:
      - name: pikabot
        image: registry.p1kachu.net:5000/pikabot
        imagePullPolicy: Always
        env:
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: swc08
              key: SLACK_TOKEN
        - name: DEFAULT_CHANNEL
          value: '#times_pikatenor'
        - name: GOOGLE_CSE_ID
          value: 007703196459396889154:-xctrzgtt98
        - name: GOOGLE_CSE_KEY
          valueFrom:
            secretKeyRef:
              name: swc08
              key: GOOGLE_CSE_KEY
        - name: LISTEN_PORT
          value: "8877"
        - name: REDIS_NAMESPACE
          value: swc08
        - name: REDIS_URL
          value: redis://redis.shared:6379/
        - name: SLACK_AUTO_RECONNECT
          value: "true"
        ports:
        - containerPort: 8877
          name: http8877
          protocol: TCP
        resources: {}
      imagePullSecrets:
      - name: p1kachu

---
apiVersion: v1
kind: Service
metadata:
  name: swc08
  namespace: pikabot
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8877
  selector:
    workload.user.cattle.io/workloadselector: deployment-pikabot-swc08
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: pikabot-swc08
  namespace: default
spec:
  externalName: swc08.pikabot.svc.cluster.local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: ExternalName

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pikabot-swc08
  namespace: default
spec:
  rules:
    - host: pikabot-swc08.app.p1kachu.net
      http:
        paths:
          - backend:
              service:
                name: pikabot-swc08
                port:
                  number: 80
            path: /
            pathType: Prefix 
  tls:
    - hosts:
        - pikabot-swc08.app.p1kachu.net
      secretName: wild-cert
