apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    app: cert-manager
    release: cert-manager
spec:
  acme:
    server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    email: pikatenor@p1kachu.net
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    - dns01:
        cloudflare:
          email: pikatenor@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-key
            key: starlight-api-key
      selector:
        matchLabels:
          "use-cloudflare-solver": "true"
    - http01:
        ingress:
          class: traefik
      selector: {}

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  labels:
    app: cert-manager
    release: cert-manager
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: pikatenor@p1kachu.net
    privateKeySecretRef:
      name: letsencrypt-production-account-key
    solvers:
    - dns01:
        cloudflare:
          email: pikatenor@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-key
            key: starlight-api-key
      selector:
        matchLabels:
          "use-cloudflare-solver": "true"
    - http01:
        ingress:
          class: traefik
      selector: {}
