apiVersion: v1
kind: ConfigMap
metadata:
  name: piko
data:
  server.yaml: |
    cluster:
      node_id_prefix: ${POD_NAME}-
      join:
        - piko
    upstream:
      auth:
        hmac_secret_key: ${PIKO_HMAC_SECRET_KEY}
