apiVersion: v1
kind: ConfigMap
metadata:
  name: piko
data:
  server.yaml: |
    cluster:
      node_id_prefix: ${POD_NAME}-
      join:
        - piko
    proxy:
      timeout: 0s
      http:
        read_timeout: 0s
        write_timeout: 0s
    upstream:
      auth:
        hmac_secret_key: ${PIKO_HMAC_SECRET_KEY}
