apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - path: configmap-auth.yaml
    target:
      kind: ConfigMap
      name: piko
  - target:
      kind: StatefulSet
      name: piko
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: PIKO_HMAC_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: piko-auth
              key: hmac-secret-key
