apiVersion: v1
kind: ServiceAccount
metadata:
  name: woodpecker-deploy
  namespace: p1kachu-net
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: woodpecker-deploy
  namespace: p1kachu-net
rules:
  - apiGroups: ["", "apps", "batch", "networking.k8s.io"]
    resources:
      - deployments
      - services
      - configmaps
      - secrets
      - jobs
      - pods
      - ingresses
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: woodpecker-deploy
  namespace: p1kachu-net
subjects:
  - kind: ServiceAccount
    name: woodpecker-deploy
    namespace: p1kachu-net
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: woodpecker-deploy
