apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-litellm-litellm-psql
  name: litellm-psql
  namespace: litellm
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-litellm-litellm-psql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-litellm-litellm-psql
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1001
      containers:
        - name: postgres
          image: "mirror.gcr.io/bitnami/postgresql:16-debian-12@sha256:233f361c5819c180b600d110d7da953bea6f1a00764752643ffb7b78ba85c628"
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: POSTGRESQL_VOLUME_DIR
              value: "/var/lib/postgresql"
            - name: PGDATA
              value: "/var/lib/postgresql/data"
            - name: POSTGRESQL_ENABLE_LDAP
              value: "no"
            - name: POSTGRES_USER
              value: "litellm"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: litellm
                  key: db-password
            - name: POSTGRESQL_DATABASE
              value: "litellm"
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            privileged: false
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 20m
              memory: 64Mi
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "$POSTGRES_USER" -h 127.0.0.1 -p 5432
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - -e
                - |
                  exec pg_isready -U "$POSTGRES_USER" -h 127.0.0.1 -p 5432
                  [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /var/lib/postgresql/.initialized ]
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: vrun
              mountPath: /var/run/postgresql
            - name: tmp
              mountPath: /tmp
            - name: litellm-psql-storage
              mountPath: /var/lib/postgresql
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 256Mi
        - name: vrun
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: litellm-psql-storage
          hostPath:
            path: /media/Hayate/litellm-psql
            type: Directory
      nodeName: juno4a
---
apiVersion: v1
kind: Service
metadata:
  name: litellm-psql
  namespace: litellm
spec:
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: postgres
  selector:
    workload.user.cattle.io/workloadselector: deployment-litellm-litellm-psql
  sessionAffinity: None
  type: ClusterIP
