apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-shared-mongodb
  name: mongodb
  namespace: shared
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-shared-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-shared-mongodb
      namespace: shared
    spec:
      containers:
        - name: mongo
          image: mongo:6
          imagePullPolicy: Always
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: USERNAME
                  name: mongo
                  optional: false
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PASSWORD
                  name: mongo
                  optional: false
          ports:
            - containerPort: 27017
              name: mongo
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: data
          resources: {}
      nodeName: rin
      volumes:
        - hostPath:
            path: /var/bind-data/mongodb
            type: DirectoryOrCreate
          name: data

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: shared
spec:
  ports:
  - name: redis
    port: 27017
    protocol: TCP
    targetPort: mongo
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-shared-mongodb
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-shared-mongo-express
  name: mongo-express
  namespace: shared
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-shared-mongo-express
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-shared-mongo-express
      namespace: shared
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          imagePullPolicy: Always
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  key: USERNAME
                  name: mongo
                  optional: false
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  key: PASSWORD
                  name: mongo
                  optional: false
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongodb
          ports:
            - containerPort: 8081
              name: http-alt
              protocol: TCP
          resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: shared
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-alt
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-shared-mongodb
  type: ClusterIP
