apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-shared-redis
  name: redis
  namespace: shared
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-shared-redis
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-shared-redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          tcpSocket:
            port: 6379
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 2
          tcpSocket:
            port: 6379
          timeoutSeconds: 2
        volumeMounts:
        - mountPath: /data
          name: data
        resources: {}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: shared-redis-data

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: shared
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    workload.user.cattle.io/workloadselector: deployment-shared-redis
  type: ClusterIP
