apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea
  namespace: default
spec:
  # storageClassName: Use the default class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
